import type { DesktopSnapshot, LocalSession, OperationEvent } from "./model";

export function operation(overrides: Partial<OperationEvent>): OperationEvent {
  return {
    apiSurface: "/v1/responses",
    attributedUsage: {
      categories: {
        conversationHistory: 320,
        currentUserInput: 40,
        instructions: 80,
        mcpDefinitions: 25,
        mcpResults: 120,
        media: 0,
        otherContext: 15,
        retrievedDocuments: 50,
        toolDefinitions: 200,
        toolResults: 150,
      },
      measurement: "estimated-chars-div-4",
      method: "structured-request-fields",
      totalEstimatedTokens: 1_000,
    },
    contentRecorded: false,
    cost: {
      canonicalModel: "gpt-5.4-2026-03-05",
      currency: "USD",
      estimated: false,
      pricingVersion: "2026-07-09",
      status: "priced",
      totalCostNanosUsd: 3_100_000,
      totalCostUsd: "0.0031",
    },
    durationMs: 420,
    harness: { confidence: 0.8, method: "user-agent", name: "codex-cli" },
    localProcessingMs: 20,
    optimization: { changedFields: 1, estimatedTokensSaved: 30 },
    outcome: "success",
    plugins: { "request-audit": "passed" },
    provider: "openai-responses",
    providerDurationMs: 400,
    providerResponseId: "resp_test",
    requestId: "request_test",
    requestedModel: "gpt-5.4",
    responseModel: "gpt-5.4-2026-03-05",
    security: { redacted: true, redactionCount: 2 },
    statusCode: 200,
    timeToFirstByteMs: 80,
    timestamp: "2026-07-09T12:00:00.000Z",
    traceId: "0123456789abcdef0123456789abcdef",
    transport: "http",
    usage: {
      cacheReadTokens: 400,
      cacheWriteTokens: 25,
      inputTokens: 900,
      outputTokens: 100,
      reasoningTokens: 20,
      totalInputTokens: 900,
      totalTokens: 1_000,
    },
    usageSource: "provider-reported",
    ...overrides,
  };
}

export function localSession(overrides: Partial<LocalSession> = {}): LocalSession {
  return {
    cachedTokens: 400,
    context: operation({}).attributedUsage.categories,
    conversationId: "conversation-openai",
    errors: 0,
    estimatedCostNanosUsd: 3_100_000,
    harness: "codex-cli",
    id: "codex-cli:conversation-openai",
    inputTokens: 900,
    lastActivityAt: "2026-07-09T12:01:00.000Z",
    messages: [],
    models: ["gpt-5.4"],
    operations: 1,
    outputTokens: 100,
    project: "cutokyo",
    provider: "openai-responses",
    reasoningTokens: 0,
    startedAt: "2026-07-09T12:00:00.000Z",
    title: "OpenAI session",
    totalTokens: 1_000,
    traceIds: ["0123456789abcdef0123456789abcdef"],
    workspace: "/workspace/cutokyo",
    ...overrides,
  };
}

const baseSnapshot: DesktopSnapshot = {
  detection: [],
  events: [
    operation({}),
    operation({
      cost: {
        canonicalModel: "claude-sonnet-4-6",
        currency: "USD",
        estimated: true,
        pricingVersion: "2026-07-09",
        status: "priced",
        totalCostNanosUsd: 5_400_000,
        totalCostUsd: "0.0054",
      },
      harness: { confidence: 1, method: "configured", name: "claude-code" },
      provider: "anthropic-messages",
      responseModel: "claude-sonnet-4-6",
      traceId: "fedcba9876543210fedcba9876543210",
      usage: {
        cacheReadTokens: 100,
        inputTokens: 400,
        outputTokens: 100,
        totalInputTokens: 400,
        totalTokens: 500,
      },
    }),
  ],
  exporter: {
    enabled: true,
    endpoint: "https://collector.example.test/v1/logs",
    exportedEvents: 2,
    lastSuccess: "2026-07-09T12:00:01.000Z",
    pendingEvents: 0,
    protocol: "http/json",
  },
  metrics: {
    compressedRequests: 2,
    liveRequests: 2,
    savingsRatio: 0.42,
    totalEstimatedTokensAfter: 900,
    totalEstimatedTokensBefore: 1_500,
    totalEstimatedTokensSaved: 600,
  },
  plugins: {
    configured: true,
    configPath: "C:\\Users\\operator\\.cutokyo\\plugins.json",
    enabled: true,
    plugins: [
      {
        command: "context-filter.exe",
        enabled: true,
        failMode: "open",
        hooks: ["request.before"],
        id: "context-filter",
        ready: true,
        timeoutMs: 750,
      },
    ],
  },
  sessions: [],
  settings: {
    apiKeyRedaction: true,
    autoConnect: true,
    compression: false,
    conversationRecording: true,
    emailRedaction: true,
    filePathRedaction: true,
    ipAddressRedaction: true,
    observability: true,
    organizationSync: true,
    otlpExport: true,
    paymentCardRedaction: true,
    phoneNumberRedaction: true,
    plugins: true,
    providerMutation: false,
  },
  session: {
    authConfigured: true,
    authenticated: true,
    user: { email: "operator@example.test", name: "Operator" },
  },
  status: {
    clients: { claude: "gateway", codex: "gateway", gemini: "gateway" },
    status: "ready",
  },
  storage: {
    blockedRecords: 0,
    degraded: false,
    encryption: "XChaCha20-Poly1305",
    keySource: "os-credential-store",
    lastWriteAt: "2026-07-09T12:00:00.000Z",
    quarantinedRecords: 0,
    records: 2,
  },
};

/** Build an isolated desktop snapshot fixture for one test. */
export function desktopSnapshot(): DesktopSnapshot {
  return structuredClone(baseSnapshot);
}
