import { vi } from "vitest";

import type { useOrganizationDashboard } from "./model";

const group = {
  createdAt: "2026-07-10T12:00:00Z",
  id: "grp_platform",
  memberIds: ["user_ada"],
  name: "Platform",
  organizationId: "org_cutokyo",
  updatedAt: "2026-07-10T12:00:00Z",
  updatedBy: "user_admin",
};

export const session = {
  cachedTokens: 80,
  conversationId: "conversation-ada",
  deviceId: "device-ada",
  errors: 0,
  estimatedCostNanosUsd: 990_000,
  harness: "codex-cli",
  id: "session-ada",
  inputTokens: 140,
  lastActivityAt: "2026-07-10T12:00:00Z",
  messageCount: 1,
  models: ["gpt-5.4"],
  operations: 2,
  outputTokens: 40,
  project: "cutokyo",
  provider: "openai-responses",
  reasoningTokens: 12,
  startedAt: "2026-07-10T11:00:00Z",
  title: "Cutokyo implementation",
  totalTokens: 304,
  userId: "user_ada",
  workspace: "/workspace/cutokyo",
};

export const operation = {
  apiSurface: "/v1/responses",
  attributedUsage: { toolResults: 50 },
  cacheReadTokens: 80,
  cacheWriteTokens: 9,
  contentRecorded: true,
  conversationId: "conversation-ada",
  costNanosUsd: 990_000,
  deviceId: "device-ada",
  durationMs: 430,
  errorType: "provider_timeout",
  estimatedTokensSaved: 12,
  harness: "codex-cli",
  harnessConfidence: 0.9,
  harnessMethod: "user-agent",
  inputTokens: 100,
  localProcessingMs: 12,
  model: "gpt-5.4",
  optimization: { algorithms: { "relevance-v1": 1 } },
  optimizationChangedFields: 2,
  outcome: "error",
  outputTokens: 40,
  plugins: { "request-audit": "ok" },
  previewState: "redacted_preview" as const,
  pricingVersion: "2026-07-09",
  project: "cutokyo",
  provider: "openai-responses",
  providerDurationMs: 418,
  providerResponseId: "response_ada",
  reasoningTokens: 12,
  redactions: 2,
  requestedModel: "gpt-5.4",
  requestId: "request_ada",
  responseModel: "gpt-5.4",
  security: { categories: { secret: 2 }, redacted: true },
  statusCode: 504,
  timeToFirstByteMs: 200,
  timestamp: "2026-07-10T12:00:00Z",
  totalInputTokens: 180,
  totalTokens: 241,
  traceId: "trace_ada",
  transport: "http",
  usageSource: "provider-reported",
  userId: "user_ada",
  workspace: "/workspace/cutokyo",
};

export const members = [
  {
    email: "ada@example.com",
    firstName: "Ada",
    id: "user_ada",
    lastName: "Lovelace",
    name: "Ada Lovelace",
    roles: ["developer"],
  },
  {
    email: "grace@example.com",
    firstName: "Grace",
    id: "user_grace",
    lastName: "Hopper",
    name: "Grace Hopper",
    roles: ["developer"],
  },
];

export const policy = {
  organizationId: "org_cutokyo",
  policy: {
    content: { rawCapture: false, redactedPreviews: true, retentionDays: 30 },
    observability: { enabled: true, otlpExport: false },
    optimization: {
      enabled: true,
      failMode: "closed" as const,
      providerMutation: true,
      shadowMode: false,
    },
    redaction: {
      apiKeys: true,
      emails: true,
      failMode: "closed" as const,
      filePaths: true,
      ipAddresses: true,
      paymentCards: true,
      phoneNumbers: true,
    },
  },
  policyVersion: 3,
  updatedAt: "2026-07-10T12:00:00Z",
  updatedBy: "user_admin",
};

export function dashboardState(): ReturnType<typeof useOrganizationDashboard> {
  return {
    data: {
      auditEvents: [],
      byDevice: [],
      byGroup: [{ costNanosUsd: 100, events: 2, name: "Platform", tokens: 304 }],
      byHarness: [],
      byModel: [],
      byProvider: [],
      byUser: [{ costNanosUsd: 100, events: 2, name: "user_ada", tokens: 304 }],
      cacheReadTokens: 20,
      context: {
        conversationHistory: 50,
        currentUserInput: 20,
        instructions: 10,
        mcpDefinitions: 0,
        mcpResults: 0,
        media: 0,
        otherContext: 4,
        retrievedDocuments: 0,
        toolDefinitions: 100,
        toolResults: 120,
      },
      devices: [],
      errorEvents: 0,
      estimatedTokensSaved: 40,
      groups: [group],
      invitations: [],
      license: {
        detail: "Licensing is disabled.",
        features: [],
        limits: {},
        mode: "disabled",
        readOnly: false,
        state: "disabled",
        wouldBlock: false,
      },
      members: [],
      organization: { id: "org_cutokyo", name: "Cutokyo Labs" },
      policy: null,
      plugins: [],
      recentEvents: [],
      sessions: [],
      totalCostNanosUsd: 100,
      totalEvents: 2,
      totalRedactions: 3,
      totalTokens: 304,
    },
    deleteGroup: vi.fn().mockResolvedValue(undefined),
    error: null,
    exportOrganizationData: vi.fn().mockResolvedValue(undefined),
    loadOperations: vi.fn().mockResolvedValue(undefined),
    loading: false,
    operationCorrelation: "",
    operationError: null,
    operationLoading: false,
    operationPage: { nextCursor: null, operations: [] },
    organizationId: "org_cutokyo",
    permissions: ["groups:read", "groups:write"],
    reportFilters: { harness: "all", model: "all", provider: "all", range: "30d" },
    saveGroup: vi.fn().mockResolvedValue(group),
    saveManagedPlugin: vi.fn().mockResolvedValue(undefined),
    savingGroup: false,
    savingPolicy: false,
    savingPlugin: false,
    selectedSessionId: null,
    sessionDetail: null,
    sessionError: null,
    sessionLoading: false,
    setSelectedSessionId: vi.fn(),
    setPolicyCapability: vi.fn(),
    setReportFilters: vi.fn(),
    setTelemetryScope: vi.fn(),
    testManagedPlugin: vi.fn().mockResolvedValue(undefined),
    telemetryScope: { kind: "all", label: "Everyone" },
    uninstallManagedPlugin: vi.fn().mockResolvedValue(undefined),
    user: { email: "ada@example.com", firstName: "Ada" },
  } as never;
}
