name: DCO

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  actions-dco:
    name: Developer Certificate of Origin
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Verify every pull-request commit sign-off
        uses: KineticCafe/actions-dco@5f160e3ee086af8fc0fb567b8add0937d074123e # v3.2.0
